---
Parameters:
  lambdaFunctionName:
    Type: String
    AllowedPattern: "[a-zA-Z0-9]+[a-zA-Z0-9-]+[a-zA-Z0-9]+"
    Default: CsEventsProcessorLambda
  lambdaDescription:
    Type: String
    Default: This lambda is executed upon new Event Outcome insertion and upon Events ending. It calculates milestone and event winners and performs the reward payout.

Resources:
  LambdaExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      Path: "/"
      Policies:
      - PolicyName: allowSqs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
            - sqs:ChangeMessageVisibility
            Resource: !GetAtt CsEventProcessorQueue.Arn        
      - PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action: dynamodb:*
            Effect: Allow
            Resource: "*"
          - Action: s3:*
            Effect: Allow
            Resource: "*"
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:CreateLogGroup
            - logs:PutLogEvents
            Resource:
            - "*"
          - Effect: Allow
            Action:
            - cloudwatch:PutMetricAlarm
            - cloudwatch:PutMetricData
            Resource:
            - "*"         
        PolicyName: root
    Type: AWS::IAM::Role

  CsEventsProcessorLambda:
    Properties:
      Description: !Ref lambdaDescription
      FunctionName: !Ref lambdaFunctionName
      Code:
        ZipFile: return;
      Handler: Services/v1/Lambdas/EventsProcessorLambda/index.handler
      MemorySize: 128
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Runtime: nodejs12.x
      Timeout: 900     
    Type: AWS::Lambda::Function

  CsEventsProcessorLambdaAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmDescription: "Alarm if the API returns any 500s"
        Namespace: "AWS/Lambda"
        MetricName: "Errors"
        Dimensions:
        - Name: "FunctionName"
          Value: "CsEventsProcessorLambda"
        Statistic: "Sum"
        ComparisonOperator: "GreaterThanThreshold"
        Threshold: 0
        EvaluationPeriods: 1
        Period: 60
        TreatMissingData: "missing"
        AlarmActions:
          - arn:aws:sns:us-west-2:903733074442:SkateXAlarms

  LambdaFunctionEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !GetAtt CsEventProcessorQueue.Arn
      FunctionName: !GetAtt CsEventsProcessorLambda.Arn

  CsEventProcessorQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      QueueName: CsEventsProcessorQueue.fifo
      DelaySeconds: 0
      VisibilityTimeout: 900
