name: "CsApiGateway"

on:
  push:
    paths:
      - Services/ApiGateway/**
    branches:
      - main
  workflow_run:
    workflows: ["AuthLambda"]
    types:
      - completed

jobs:
  CsApiGateway:
    name: "ApiGateway Production Deployment"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Credential Setup
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy ApiGateway Infra
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: CsApiGateway
          template: Services/ApiGateway/main.yml
          no-fail-on-empty-changeset: "1"